name: ci

on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
  pull_request:
    branches:
      - master
      - releases/v*
  push:
    branches:
      - master
      - releases/v*

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containerd-version:
          - latest
          - v1.4.1
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.2
      -
        name: Set up containerd
        uses: ./
        with:
          containerd-version: ${{ matrix.containerd-version }}
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1
